name: itshoppeapp
description: "A new Flutter project."
publish_to: 'none' # This line prevents the package from being published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  lottie: ^2.2.0
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/itlogo.png
    - assets/animations/Success.json
    - assets/animations/cart.json
    - assets/animations/wrong.json
    - assets/animations/Userhead.json
    - assets/animations/ok.json
